# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b551fa2c972e9667ded18b3fab7d4cde376b958df258a9bed054d41d2792f3ae4a3c0ce4a71a2a902d81d3cd930661dc8fe39afb6e8ef8bad6ae11052751d016

test:
  secret_key_base: 2c15c09e89acf334529d700078e78ae2e1b16689b12322f8cfb089d9399b7af14e5de7791648c4f95a40a218520b4b47093c9cfd403ca1d0ce44059e54eb8a47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
